#!/bin/bash 
echo "SEMESTER LaTeX PREP"
echo "This bash script is for creating organized directories "
echo "for an eight week semester using the student's name, class"
echo "and week of class. Each folder will contain a matching"
echo "LaTeX tex file and BibTeX bib file. To begin enter the class"
echo "name: ";
read CLASS;
echo "You submitted: $CLASS";
echo "Enter your first two initials and last name in one string: "
read youN
echo "Make LaTeX directory for $CLASS in current directory?"
pwd
echo "Enter y/n and press [ENTER]: "; 
read reply;
if [ $reply = "y" ]; then
mkdir -v -p  "$CLASS/"{WK1/{Post1,Post2,Post3,Post4,Essay},WK2/{Post1,Post2,Post3,Post4,Essay},WK3/{Post1,Post2,Post3,Post4,Essay},WK4/{Post1,Post2,Post3,Post4,Essay},WK5/{Post1,Post2,Post3,Post4,Essay},WK6/{Post1,Post2,Post3,Post4,Essay},WK7/{Post1,Post2,Post3,Post4,Essay},WK8/{Post1,Post2,Post3,Post4,Essay}};
echo "Paste full path to a tex document which will be used as a template."
echo "For example \home\texCrazyGuy\Documents\MyTemplate.tex"
echo "Paste and the hit [ENTER]: "
read template
week=1 
while [ $week -le 8 ]
do
touch "$CLASS/WK$week/Post1/$youN-$CLASS-WK$week-Post1.bib"
cat $template >> "$CLASS/WK$week/Post1/$youN-$CLASS-WK$week-Post1.tex"
touch "$CLASS/WK$week/Post2/$youN-$CLASS-WK$week-Post2.bib"
cat $template >> "$CLASS/WK$week/Post2/$youN-$CLASS-WK$week-Post2.tex"
touch "$CLASS/WK$week/Post3/$youN-$CLASS-WK$week-Post3.bib"
cat $template >> "$CLASS/WK$week/Post3/$youN-$CLASS-WK$week-Post3.tex"
touch "$CLASS/WK$week/Post4/$youN-$CLASS-WK$week-Post4.bib"
cat $template >> "$CLASS/WK$week/Post4/$youN-$CLASS-WK$week-Post4.tex"
touch "$CLASS/WK$week/Essay/$youN-$CLASS-WK$week-Essay.bib"
cat $template >> "$CLASS/WK$week/Essay/$youN-$CLASS-WK$week-Essay.tex"
week=$(($week + 1))
done
echo "Here are your new fancy LaTeX ready subdirectories: "
ls -R $CLASS
else 
echo "Quitting without making directory...";
fi


